apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
    release: '1'  
spec:
  containers:
    - name: fleetman-queue
      image: richardchesterwood/k8s-fleetman-queue:release1          